### ISSUE TITLE
New default panel settings

### ISSUE THREAD

**Issue by KateKraft** [KwatME/match#10]
I played around with these parameters with long features names and short feature names, and found these settings will avoid cutting any test/numbers off with the exception of some super long pathway or target names:

layout_width=1080
layout_side_margin=230
annotation_font_size=9

I know those numbers don't fit your special rule, but for each of them I tried slightly higher and lower, and choose these numbers for a reason.

**Comment by KwatME** [comment]
Sounds good. I can update the code to have these as the default :) If things don't look good, we can change it later.
