### ISSUE TITLE
Feature request for n_required_for_match_function

### ISSUE THREAD

**Issue by KateKraft** [KwatME/match#5]
Right now you can pass in "n_required_for_match_function" into make_match_panel, or make_match_panels as a **kwarg. 

But it would be nice to be able to tell both functions to make "n_required_for_match_function" always equal to the length of whatever target is currently being matched to. 

Why do this? Because when you pass in many targets, some may include 50 samples, but some may only include 10. So if you set "n_required_for_match_function" equal to 50, match will fail when it matches to targets with less than 50 samples.

**Comment by KwatME** [comment]
Done. Thanks for the input :)
