### ISSUE TITLE
n_required_for_match_function in make_match_panels function

### ISSUE THREAD

**Issue by KateKraft** [KwatME/match#6]
If **overwrite=False** and you pass **n_required_for_match_function** into the **make_match_panels** function, the panels that are produced don't abide by the n_required_for_match_function that was set. For example if n_required_for_match_function=10, match panels with only 5 or 6 real values in a feature will be shown in the match panels.

**Comment by KwatME** [comment]
`overwrite=False` uses whatever score produced by the previous run (`scores` will be loaded if the file exists). Since altering `n_required_for_match_function` alters the results, make sure to recompute to get a new results (`overwrite=True`).
